config/routes.rb
NewReader::Application.routes.draw do
  resources :feeds, only: [:index, :create, :show] do
    resources :entries, only: [:index]
  end

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  root to: "feeds#index"
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :guid, :link, :published_at, :title, :json, :feed_id

  belongs_to :feed

  def self.create_from_json!(entryData, feed)
    Entry.create!({
      guid: entryData.guid,
      link: entryData.link, 
      published_at: entryData.pubDate,
      title: entryData.title, 
      json: entryData,
      feed_id: feed.id
    })
  end
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  attr_accessible :title, :url, :user_id

  validates :title, :url, :user_id, presence: true

  has_many :entries, :dependent => :destroy
  belongs_to :user

  def self.find_or_create_by_url(url, id)
    feed = Feed.find_by_url(url)
    return feed if feed

    begin
      feed_data = SimpleRSS.parse(open(url))
      feed = Feed.create!(title: feed_data.title, url: url, user_id: id)
      feed_data.entries.each do |entry_data|
        Entry.create_from_json!(entry_data, feed)
      end
    rescue SimpleRSSError
      return nil
    end

    feed
  end

  # def as_json(options) # { created_at: ..., id:, ... }
  #   super(options).merge({ entries: self.entries })
  # end

  def reload
    # reloads entries
    self.touch #this causes the updated_at column to be updated
    begin
      feed_data = SimpleRSS.parse(open(url))
      existing_entry_guids = Entry.pluck(:guid).sort
      feed_data.entries.each do |entry_data|
        unless existing_entry_guids.include?(entry_data.guid)
          Entry.create_from_json!(entry_data, self)
        end
      end

      self
    rescue SimpleRSSError
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :session_token

  validates :username, :password, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 3 }

  has_many :feeds

  def self.find_by_username_and_password(username, password)

    @user = User.find_by_username(username)

    if @user && @user.is_password(password)
      return @user
    else
      return nil
    end
  end

  def is_password(password)
    return (self.password == password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def current_user
    @user ||= User.find_by_session_token(session[:session_token])
  end

  def log_in_user(user)
    user.session_token = SecureRandom::urlsafe_base64(16)
    session[:session_token] = user.session_token
    user.save!
  end


end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    feed = Feed.find(params[:feed_id])
    render :json => feed.entries
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feeds = current_user.feeds

    @feeds.each do |feed|
      if feed.entries.length > 0
        last_update_time = feed.entries.last.updated_at
        if ((Time.now - last_update_time) > 120)
          feed.reload
        end
      else
        feed.reload
      end
    end

    if request.xhr?
      render :json => @feeds.to_json(:include => :entries)
    end
    # respond_to do |format|
#       format.html { render :index }
#       format.json { render :json => @feeds.to_json(:include => :entries) }
#     end
  end

  def create
    @feed = Feed.find_or_create_by_url(params[:feed][:url], current_user.id)

    if request.xhr?
      if @feed
        render :json => @feed
      else
        render :json => { error: "invalid url" }, status: :unprocessable_entity
      end
    else
      redirect_to feeds_url
    end
  end

  def show
    @feed = Feed.find(params[:id])
    @feed.reload

    if request.xhr?
      render json: @feed.to_json(:include => :entries) # {@feed, @entries}
    else
      render :show
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_username_and_password(
    params[:user][:username],
    params[:user][:password]
    )

    if @user
      log_in_user(@user)
      redirect_to feeds_url
    else
      flash.now[:errors] = ["WRONG CREDENTIALS"]
      render :new
    end
  end

  def destroy

    session[:session_token] = nil
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      log_in_user(@user)
      redirect_to feeds_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/index.html.erb
<h1>Hello World</h1>
<div id='content'>

</div>

<form action="feeds" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" id="authenticity_token">

<label>Feed Title:
  <input type="text" name="feed[title]" value="">
</label>
<br>
<label>Feed URL:
  <input type="text" name="feed[url]" value="">
</label>
<br>

<input type="submit" value="Add Feed!">
</form>

<script>

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewReader</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    <p>Logged in as <%= current_user.username %></p>
    <%= button_to "Logout", session_url, method: :delete %>
  <% else %>

  <div class="errors">
    <%= flash[:errors]%>
  </div>

  <%= button_to "Sign Up", new_user_url, method: :get %>
  <%= button_to "Sign In", new_session_url, method: :get%>
  <% end %>




<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%=users_url%>" method="post">

  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>" id="authenticity_token">

<label>Username
  <input type="text" name="user[username]" value="" id="user[username]">
</label>
<br>

<label>Password
  <input type="password" name="user[password]" value="" id="user[password]">
</label>
<br>

<input type="submit" name="some_name" value="Submit" id="some_name">

</form>